name: python app

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run tests
        run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-world
          path: .
